# FROM node:20-bookworm-slim AS deps
# WORKDIR /app
# RUN corepack enable

# COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./
# COPY backend/package.json backend/package.json

# RUN pnpm -C backend install --frozen-lockfile


# FROM node:20-bookworm-slim AS builder
# WORKDIR /app

# RUN npm install -g bun

# COPY --from=deps /app/node_modules /app/node_modules
# COPY --from=deps /app/backend/node_modules /app/backend/node_modules

# COPY backend/tsconfig.json backend/tsconfig.json
# COPY backend/src backend/src
# COPY backend/package.json backend/package.json
# RUN corepack enable && pnpm -C backend run build:compile

# FROM gcr.io/distroless/base-debian12:debug AS runner

# WORKDIR /app

# COPY --from=builder /app/backend/backend /app/backend

# EXPOSE 1337
# ENV NODE_ENV=production
# CMD ["/app/backend"]

FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

RUN pnpm install -g bun@latest

FROM base AS builder

WORKDIR /app

RUN pnpm add -g turbo
COPY . .
RUN turbo prune backend --docker

FROM base AS installer
WORKDIR /app

COPY --from=builder /app/out/json/ .
RUN pnpm install

COPY --from=builder /app/out/full/ .

RUN pnpm turbo build:compile

FROM gcr.io/distroless/base-debian12:debug AS runner

WORKDIR /app

EXPOSE ${PORT:-1337}
ENV NODE_ENV=${NODE_ENV:-production}
CMD ["backend/dist/bin"]