FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder

WORKDIR /app

RUN pnpm add -g turbo
COPY . .
RUN turbo prune web --docker

FROM base AS installer
WORKDIR /app

COPY --from=builder /app/out/json/ .
RUN pnpm install

COPY --from=builder /app/out/full/ .

RUN pnpm turbo build

FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 ssmb
RUN adduser --system --uid 1001 ssmb
USER ssmb
COPY --from=installer /app .

EXPOSE 3000
CMD ["node", "web/.output/server/index.mjs", "--host", "0.0.0.0", "--port", "3000"]