name: super-smash-mobs-brawl

services:
  postgres:
    image: postgres:18
    container_name: ssmb-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-brawl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-brawl}
      POSTGRES_DB: ${POSTGRES_DB:-brawl}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  migrate:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.migrate
    container_name: ssmb-migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}"
    command: ["bun", "run", "db:migrate"]
    restart: "no"
  redis:
    image: redis:latest
    container_name: ssmb-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_USER: ${REDIS_USER:-default}
      REDIS_DB: ${REDIS_DB:-0}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: ssmb-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-changeme}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000/api/auth}
      POLAR_ACCESS_TOKEN: ${POLAR_ACCESS_TOKEN:-}
      POLAR_SUCCESS_URL: ${POLAR_SUCCESS_URL:-http://localhost:3000/checkout/success}
      POLAR_SERVER: ${POLAR_SERVER:-sandbox}
      PLUGIN_SECRET_KEY: ${PLUGIN_SECRET_KEY:-changeme}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}"
  minecraft:
    build:
      context: ./plugin
      dockerfile: Dockerfile
    container_name: ssmb-minecraft
    restart: unless-stopped
    ports:
      - "${MINECRAFT_PORT:-25565}"
    environment:
      MEMORY_SIZE: ${MINECRAFT_MEMORY:-2G}
      ONLINE_MODE: ${ONLINE_MODE:-false}
      MINECRAFT_PORT: ${MINECRAFT_PORT:-25565}
      AXIOM_API_TOKEN: ${AXIOM_API_TOKEN:-}
      AXIOM_DATASET_NAME: ${AXIOM_DATASET_NAME:-super-smash-mobs-brawl}
      BASE_API_URL: ${BASE_API_URL:-http://localhost:3000}
      API_SECRET_KEY: ${API_SECRET_KEY:-changeme}
    stdin_open: true
    tty: true

volumes:
  db_data:
