FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder

WORKDIR /app

RUN pnpm add -g turbo
COPY . .
RUN turbo prune backend --docker

FROM base AS installer
WORKDIR /app

COPY --from=builder /app/out/json/ .
RUN pnpm install

COPY --from=builder /app/out/full/ .

RUN npm install -g bun
RUN pnpm turbo build:compile

FROM oven/bun:latest AS runner

WORKDIR /app

COPY --from=installer /app/backend/dist/backend ./backend

EXPOSE 1337
ENV NODE_ENV=production

RUN chmod +x backend
CMD ["./backend"]