FROM oven/bun:latest AS base

WORKDIR /usr/src/app

FROM base AS deps

COPY package.json ./

RUN bun install

RUN bun install postgres

FROM deps AS migrate

COPY . .

CMD ["bun", "run", "db:migrate"]