name: autofix.ci

on:
  push:
    branches: ["main", "reimagined"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run Ktfmt
        run: bunx ktfmt@latest --kotlinlang-style plugin/src

      - name: Run Prettier
        run: bun run format

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
