name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main", "reimagined"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Ktfmt
        run: pnpm dlx ktfmt@latest --kotlinlang-style plugin/src

      - name: Run Prettier
        run: pnpm run format

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
