name: Build Services

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "web/**"
      - "brawlie/**"
      - "packages/**"
      - ".github/workflows/build-services.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build services
        run: pnpm run build
