name: Handle Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build services
        run: pnpm run build

      - name: Test services
        run: pnpm run test

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: "Extract Meta Values"
        run: pnpm -s extract-meta > extracted-meta.json

      - name: Get short SHA
        id: get_short_sha
        run: echo ::set-output name=short-sha::${GITHUB_SHA::8}

      - name: "Create release"
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_short_sha.outputs.short-sha }}
          files: |
            ./plugin/target/*.jar
            extracted-meta.json
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
