name: "release-plugin"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "21"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: "Create release"
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./plugin/target/*.jar
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
