name: "release-plugin"

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "plugin/**"
      - ".github/workflows/release-plugin.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "maven"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: Get short SHA
        id: get_short_sha
        run: echo ::set-output name=short-sha::${GITHUB_SHA::8}

      - name: "Create release"
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.get_short_sha.outputs.short-sha }}
          files: ./plugin/target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
