name: "release-plugin"

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "plugin/**"
      - ".github/workflows/release-plugin.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: "Build with Maven"
        run: mvn package -f ./plugin/pom.xml

      - name: "Create release"
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          generated_release_notes: true
          files: ./plugin/target/*.jar
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
